import fs from 'node:fs';
import path from 'node:path';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
const enabled=!!process.env.ALTARA_PTBR_PLAYWRIGHT&&!!process.env.ALTARA_WIDGET_SITE_URL;
test('creators update an existing project by link or file without replacing earlier releases', {skip:!enabled}, async()=>{
  const {chromium}=createRequire(import.meta.url)(process.env.ALTARA_PTBR_PLAYWRIGHT);
  const browser=await chromium.launch({executablePath:process.env.ALTARA_PTBR_CHROME,headless:true});
  try {
    const context=await browser.newContext({viewport:{width:1360,height:1100}}), actor='00000000-0000-4000-8000-000000000001';
    const exp=Math.floor(Date.now()/1000)+3600,user={id:actor,aud:'authenticated',role:'authenticated',app_metadata:{},user_metadata:{}};
    const token=[{alg:'HS256',typ:'JWT'},{sub:actor,aud:'authenticated',role:'authenticated',exp},'test-signature'].map((v,i)=>i<2?Buffer.from(JSON.stringify(v)).toString('base64url'):v).join('.');
    await context.addInitScript(({user,token,exp})=>window===window.top&&localStorage.setItem('sb-tbbgwjmmaiclkhssimhf-auth-token',JSON.stringify({access_token:token,refresh_token:'test-refresh',token_type:'bearer',expires_at:exp,expires_in:3600,user})),{user,token,exp});
    const original={id:'00000000-0000-4000-8000-000000000009',author_id:actor,kind:'hosted',sdkVersion:2,name:'STREAK COUNTER',description:'Count your streak',version:'1.0.0',manifest_url:'https://widget.example.com/manifest.json',entry_url:'https://widget.example.com/index.html',permissions:['storage'],status:'published'};
    const rows=[original], writes=[], errors=[];let failLatest=false;
    if(process.env.ALTARA_WIDGET_SOURCE) await context.route('**/widget-assets/*.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(process.env.ALTARA_WIDGET_SOURCE,path.basename(new URL(route.request().url()).pathname)),'utf8')}));
    await context.route('https://tbbgwjmmaiclkhssimhf.supabase.co/**',async route=>{
      const request=route.request(),url=new URL(request.url()); let body=[];
      if(url.pathname.endsWith('/user'))body=user;
      else if(url.pathname.includes('/home_widget_releases')){
        if(failLatest && url.searchParams.get('select')==='snapshot_sha256,permissions')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Test latest-release failure'})});
        if(request.method()==='POST'){
          const payload=request.postDataJSON();writes.push(payload);
          rows.unshift({...payload,id:`00000000-0000-4000-8000-${String(10+writes.length).padStart(12,'0')}`,status:'published'});
        }
        assert.notEqual(request.method(),'PATCH','publishing must not overwrite old releases');
        const filtered=url.searchParams.has('id')?rows.filter(row=>'eq.'+row.id===url.searchParams.get('id')):rows;
        body=request.headers().accept?.includes('object')?filtered[0]:filtered;
      }else if(url.pathname.includes('/rpc/widget_marketplace_details'))body=rows.map(row=>({id:row.id,author_id:actor,creator_name:'Test Maker',creator_username:'maker',downloads:2,rating_count:1,rating_average:5}));
      else if(request.method()==='POST'&&url.pathname.includes('/install'))throw Error('Publishing must not update installations');
      await route.fulfill({contentType:'application/json',body:JSON.stringify(body),headers:{'access-control-allow-origin':'*'}});
    });
    await context.route('https://widget.example.com/manifest.json',route=>route.fulfill({contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify({manifest_version:1,name:'Different manifest title',description:'Different description',version:'1.1.0',entry:'./index.html',permissions:['storage']})}));
    await context.route('https://new-host.example.com/**',route=>route.fulfill({contentType:route.request().url().endsWith('.json')?'application/json':'text/html',headers:{'access-control-allow-origin':'*'},body:route.request().url().endsWith('.json')?'{}':'<h1>Version 2</h1>'}));
    const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));
    page.on('response',response=>{if(new URL(response.url()).pathname.endsWith('.css')&&!response.ok())errors.push('Styles failed: '+response.status());});
    await page.goto(process.env.ALTARA_WIDGET_SITE_URL+'/developers/widgets');
    await page.getByRole('button',{name:'Published widgets',exact:true}).click();
    await page.getByRole('button',{name:'Publish update',exact:true}).click();
    await page.getByRole('heading',{name:'Update STREAK COUNTER',exact:true}).waitFor();
    await page.waitForFunction(()=>document.querySelector('[name=version]')?.value==='1.1.0');
    assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),original.name);
    assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),original.description);
    assert.equal(await page.getByLabel('Release link (.html)',{exact:true}).inputValue(),'https://widget.example.com/release.html');
    assert.equal(await page.getByLabel('Internet APIs',{exact:true}).inputValue(),'blocked');
    const publish=page.getByRole('button',{name:'Publish update',exact:true});
    assert.equal(await publish.isDisabled(),true);
    await page.getByLabel('Release link (.html)',{exact:true}).fill('https://new-host.example.com/manifest.json');
    await page.getByRole('button',{name:'Load release',exact:true}).click();
    await page.getByText('Use the release.html link, not the manifest or a download page.',{exact:true}).waitFor();
    assert.equal(await publish.isDisabled(),true);
    await page.getByLabel('Release link (.html)',{exact:true}).fill('https://new-host.example.com/release.html');
    await page.getByRole('button',{name:'Load release',exact:true}).click();
    await page.getByText('Update ready. Publishing keeps the previous release available to installed users.',{exact:true}).waitFor();
    assert.equal(await page.locator('iframe').count(),0,'loading text does not execute the widget');
    assert.equal(await page.getByRole('button',{name:'Preview update',exact:true}).isDisabled(),true);
    await page.getByLabel('New version',{exact:true}).fill('1.0.0');assert.equal(await publish.isDisabled(),true);
    await page.getByLabel('New version',{exact:true}).fill('1.1.0');assert.equal(await publish.isDisabled(),true,'update notes are required');
    const notes=page.getByLabel('What’s new',{exact:true});
    await notes.fill('          ');assert.equal(await publish.isDisabled(),true,'whitespace is not an explanation');
    await notes.fill('Fix');assert.equal(await publish.isDisabled(),true,'short filler is rejected');
    const changes='Added a daily reset.\nFixed saved streaks. <img src=x onerror=alert(1)>';
    await notes.fill(changes);assert.equal(await publish.isDisabled(),false);
    if(process.env.ALTARA_WIDGET_EVIDENCE){fs.mkdirSync(process.env.ALTARA_WIDGET_EVIDENCE,{recursive:true});await page.screenshot({path:path.join(process.env.ALTARA_WIDGET_EVIDENCE,'creator-update-desktop.png'),fullPage:true});}
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'update form fits mobile');
    if(process.env.ALTARA_WIDGET_EVIDENCE)await page.screenshot({path:path.join(process.env.ALTARA_WIDGET_EVIDENCE,'creator-update-mobile.png'),fullPage:true});
    await publish.click();
    await page.getByText('Version 1.1.0 published. Users can find it in Check for updates.',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Publish update',exact:true}).waitFor();
    assert.equal(writes.length,1);assert.equal(rows.length,2);
    assert.equal(writes[0].snapshot_html,'<h1>Version 2</h1>');assert.match(writes[0].snapshot_sha256,/^[a-f0-9]{64}$/);
    assert.equal(writes[0].manifest_url,original.manifest_url);assert.equal(writes[0].entry_url,original.entry_url);
    assert.equal(writes[0].name,original.name);assert.equal(writes[0].version,'1.1.0');
    assert.equal(writes[0].release_notes,changes);
    assert.deepEqual(writes[0].permissions,['storage']);
    assert.equal(original.version,'1.0.0');assert.equal(original.snapshot_html,undefined);
    assert.equal(await page.getByRole('button',{name:'Publish update',exact:true}).count(),1,'one update action per project');
    await page.getByText('Earlier versions',{exact:true}).click();
    assert.equal(await page.getByRole('button',{name:'Manage publication',exact:true}).count(),2);
    await page.getByRole('button',{name:'Manage publication',exact:true}).first().click();
    await page.getByRole('heading',{name:'What’s new in v1.1.0',exact:true}).waitFor();
    assert.equal(await page.locator('.widgetReleaseNotes p').textContent(),changes);
    assert.equal(await page.locator('.widgetReleaseNotes img').count(),0,'notes are plain text, never HTML');
    await page.getByRole('button',{name:'Publish update',exact:true}).click();
    await page.getByRole('heading',{name:'Update STREAK COUNTER',exact:true}).waitFor();
    assert.equal(await page.getByLabel('New version',{exact:true}).inputValue(),'1.1.1');
    assert.equal(await notes.inputValue(),'','every update needs fresh notes');
    await notes.fill('Improved the counter layout on small screens.');
    await page.getByLabel('Release link (.html)',{exact:true}).fill('https://unavailable.example.com/release.html');
    const sameFile={name:'release.html',mimeType:'text/html',buffer:Buffer.from('<h1>Version 2</h1>')};
    failLatest=true;
    await page.locator('[name=release]').setInputFiles(sameFile);
    await page.getByText('Could not check the latest release. Try again before publishing.',{exact:true}).waitFor();
    assert.equal(await publish.isDisabled(),true,'latest-release read failures cannot bypass the check');
    failLatest=false;
    await page.locator('[name=release]').setInputFiles(sameFile);
    await page.getByText('No changes to the widget code or permissions. Upload a changed release or change its permissions.',{exact:true}).waitFor();
    assert.equal(await publish.isDisabled(),true,'a higher version and fresh notes do not make identical code an update');
    await page.getByLabel('Title',{exact:true}).fill('Renamed counter');
    assert.equal(await publish.isDisabled(),true,'renaming does not bypass the unchanged-release check');
    await page.getByLabel('Title',{exact:true}).fill(original.name);
    assert.equal(writes.length,1);
    await page.getByLabel('Internet APIs',{exact:true}).selectOption('allowed');
    assert.equal(await publish.isDisabled(),true,'changing permissions invalidates the prepared preview');
    await page.locator('[name=release]').setInputFiles(sameFile);
    await page.getByText('Update ready. Publishing keeps the previous release available to installed users.',{exact:true}).waitFor();
    await publish.click();
    await page.getByText('Version 1.1.1 published. Users can find it in Check for updates.',{exact:true}).waitFor();
    assert.equal(writes.length,2);assert.equal(writes[1].snapshot_html,writes[0].snapshot_html,'permission-only updates retain identical code');
    assert.equal(writes[1].snapshot_sha256,writes[0].snapshot_sha256);
    assert.equal(writes[1].manifest_url,original.manifest_url);
    assert.deepEqual(writes[1].permissions,['storage','network']);
    await page.getByRole('button',{name:'Publish update',exact:true}).click();
    await page.getByRole('heading',{name:'Update STREAK COUNTER',exact:true}).waitFor();
    await notes.fill('A new implementation with unchanged permissions.');
    await page.locator('[name=release]').setInputFiles({name:'release.html',mimeType:'text/html',buffer:Buffer.from('<h1>Version 3</h1>')});
    await page.getByText('Update ready. Publishing keeps the previous release available to installed users.',{exact:true}).waitFor();
    rows.unshift({...rows[0],id:'00000000-0000-4000-8000-000000000100',version:'1.1.2',snapshot_html:'<h1>Version 3</h1>',snapshot_sha256:(await import('node:crypto')).createHash('sha256').update('<h1>Version 3</h1>').digest('hex')});
    await publish.click();
    await page.getByText('No changes to the widget code or permissions. Upload a changed release or change its permissions.',{exact:true}).waitFor();
    assert.equal(writes.length,2,'publication rechecks a release prepared before another publication');
    assert.equal(await publish.isDisabled(),true);
    await page.goto(process.env.ALTARA_WIDGET_SITE_URL+'/marketplace?widget='+rows[1].id);
    await page.getByRole('heading',{name:'What’s new in v1.1.1',exact:true}).waitFor();
    assert.equal(await page.locator('.widgetReleaseNotes p').textContent(),'Improved the counter layout on small screens.');
    assert.equal(await page.getByRole('button',{name:'Add to ALTARA',exact:true}).isDisabled(),true,'notes are visible before consent and installation');
    if(process.env.ALTARA_WIDGET_EVIDENCE)await page.screenshot({path:path.join(process.env.ALTARA_WIDGET_EVIDENCE,'update-notes-before-install.png'),fullPage:true});
    assert.deepEqual(errors,[]);
  } finally {await browser.close();}
});
